# KEYS TO COSTUM SPLITS
RANDOM_SPLIT = "random"

# COSTUM ACCESS KEYS FOR CALIBRATION JSON 
focal_spot_enu_4d = "focal_spot_enu"
"""Key to acces the focal spot's center in enu coordinates."""
unblocked_focal_spot_enu_4d = "unblocked_focal_spot_enu"
"""Key to acces the focal spot's center in enu coordinates."""
ideal_focal_spot_enu_4d = "ideal_focal_spot_enu"
"""Key to access the ideal focal spot's center in enu coordinates."""

# ACCESS KEYS FOR DATALOADER CLASS
field_sample_calibration_ids = "calibration_ids"
"""Key to access the calibration IDs for the heliostat field sample."""
field_sample_sun_azimuths = "sun_azimuths"
"""Key to access the sun azimuths for the heliostat field sample."""
field_sample_sun_elevations = "sun_elevations"
"""Key to access the sun elevations for the heliostat field sample."""
field_sample_sun_positions = "sun_positions"
"""Key to access the sun positions for the heliostat field sample."""
field_sample_flux_centers = "flux_centers"
"""Key to access the flux centers for the heliostat field sample."""
field_sample_ideal_flux_centers = "ideal_flux_centers"
"""Key to access the ideal flux centers for the heliostat field sample."""
field_sample_motor_positions = "all_motor_positions"
"""Key to access the motor positions for the heliostat field sample."""
field_sample_incident_rays = "incident_ray_directions"
"""Key to access the incident ray directions for the heliostat field sample."""
field_sample_target_names = "receiver_target_names"
"""Key to access the receiver target names for the heliostat field sample."""
field_sample_flux_images = "flux_images"
"""Key to access the flux images for the heliostat field sample."""

# RUN-CONFIG ACCESS KEYS
# Top-level
run_config_general = "general"
"""Top-level key to access general run settings."""
run_config_dataset = "dataset"
"""Top-level key to access dataset split configuration."""
run_config_model = "model_settings"
"""Top-level key to access model training and scheduler configuration."""
run_config_initial_errors = "introduce_random_errors_to_scenario"
"""Top-level key to access configuration for introducing random errors to the scenario."""

# general
general_name = "name"
"""Key to access the name for model identification."""
general_scenario_path = "scenario_path"
"""Key to access the file path of the scenario HDF5 file."""
general_save_to_directory = "save_to_directory"
"""Key to access the directory where results are saved."""
general_use_raytracing = "use_raytracing_bool"
"""Key to indicate whether to use ray tracing (1) or not (0)."""
general_loss_config = "loss_config"
"""Key to access the configurations of the loss function."""
general_loss_type = "loss_for_alignment"
""""Key to indicate loss type ['MAE', 'MSE', 'MAX', 'HUBER-delta', 'QUANTILE-quantile', etc.].
The delta of Huber (default 'HUBER-0.00005') and a costum quantile (default 'QUANTILE-90') can be configured."""
general_loss_groundtruth = "ground-truth"
"""Either 'non-ideal' (should be default) or 'ideal', where 'non-ideal' is the approximated reflection axis from COM centroid and 
'ideal' loads the ideal-centroid coordinates to compute the original reflection axis for the training data."""
general_loss_basis = "alignment_loss_basis"
"""Key to indicate the mode of calculating flux centers for the predicted data ['orientation', 'center_of_mass']."""
general_contour_config = "upper_contour_config"
"""Key to access configurations for upper contour-based loss term."""
general_use_contour = "use_upper_contour_bool"
"""Key to indicate whether to look for contours and use as image loss (1) or not (0)."""
general_use_center = "use_centers_of_mass"
"""Key to indicate whether to use loss on centers of mass of contours (1) or not (0)."""
general_contour_warmup = "use_after_n_epochs"
"""Key to indicate how many epochs to wait before contour-based loss term becomes effective (warum-up)."""
general_contour_fine = "fine_alignment_with"
"""Key to indicate what function should be used for fine alignment (overlap of contours). Set '0' for not using this.
Options: Pixel-wise MSE (Set 'MSE'), Dice Intersection Loss (Set 'DICE')"""
general_contour_coarse = "coarse_alignment_with"
"""Key to indicate what function should be used for coarse alignment (no-overlap of contours). Set '0' for not using this.
Options: Chamfer-Distance (Set 'CHD'), Soft Contour-to-Distance Field Loss (Set 'SDF')"""
general_use_chd = "use_chamfer_distance_bool"
"""Key to indicate whether to use Chamfer Distance for coarse contour alignment (1) or not (0)."""
general_early_stop = "early_stopping"
"""Key to access the conditions for early stopping on validation error metric."""
general_tolerance_mrad = "tolerance_mrad"
"""Key to access the tolerated error for average alignment (val) of worst heliostat which triggers early stopping."""
general_least_improvement_mrad = "least_improvement_mrad"
"""Key to access the lower limit for improvement in field alignment error (val) over 500 epochs, below which training is stopped."""
general_introduce_random_errors = "introduce_random_errors_bool"
"""Key to indicate whether random errors should be introduced into the scenario."""
general_logging_steps = "logging_steps"
"""Key to access the number of steps between logging outputs."""
general_random_seed = "random_seed"
"""Key to access the seed used for random number generation."""
general_device = "device"
"""Key to access the computing device used for calibration (e.g., 'cuda:0')."""

# dataset and splits
dataset_training_data_directory = "training_data_directory"
"""Key to access the directory containing training data."""
dataset_training_data_was_simulated = "training_data_was_simualted_bool"
"""Key to indicate if the training data was simulated (1) or `PAINT` data (0)."""
dataset_metadata_path = "path_to_metadata"
"""Key to access the path to metadata used for dataset splits."""
dataset_load_flux_images = "load_flux_images_bool"
"""Key to indicate whether to load all flux images (higher memory use)."""
dataset_preload_flux_images = "preload_flux_images_bool"
"""Key to indicate whether to preload all flux images (keeps flux images in memory)."""
dataset_training_sizes = "training_sizes"
"""Key to access the list of training set sizes for dataset splitting."""
dataset_validation_sizes = "validation_sizes"
"""Key to access the list of validation set sizes for dataset splitting."""
dataset_split_types = "split_types"
"""Key to access the type(s) of dataset splitting method(s) used (e.g., 'knn')."""
dataset_properties_suffix = "properties_file_ends_with"
"""Key to access the expected suffix of calibration properties JSON files."""
dataset_flux_suffix = "flux_file_ends_with"
"""Key to access the expected suffix of flux image files."""
dataset_device = "device"
"""Key to access the device for loading the calibration dataset."""

# model_settings
model_optimizer = "optimizer_type"
"""Key to access the type of optimizer used for model training."""
model_initial_lr = "initial_lr"
"""Key to access the initial learning rate for training."""
model_weight_decay = "weight_decay"
"""Key to access the weight decay (L2 regularization) factor."""
model_scheduler_sequence = "scheduler_sequence"
"""Key to access the list of learning rate schedulers used in sequence."""
model_epochs_sequence = "epochs_sequence"
"""Key to access the list of epoch counts for each scheduler phase."""
model_optimizer_sgd = "SGD"
"""Key to access the SGD optimizer configuration."""
model_sgd_momentum = "momentum"
"""Key to access the momentum value used in SGD."""
model_sgd_nesterov = "nesterov"
"""Key to indicate whether Nesterov momentum is used in SGD."""
model_optimizer_rmsprop = "RMSprop"
"""Key to access the RMSprop optimizer configuration."""
model_rmsprop_alpha = "alpha"
"""Key to access the smoothing constant alpha in RMSprop."""
model_rmsprop_momentum = "momentum"
"""Key to access the momentum used in RMSprop."""
model_rmsprop_centered = "centered"
"""Key to indicate whether RMSprop uses centered gradients."""
model_optimizer_adam = "Adam"
"""Key to access the Adam optimizer configuration."""
model_adam_betas = "betas"
"""Key to access the beta parameters used in Adam."""
model_optimizer_adamw = "AdamW"
"""Key to access the AdamW optimizer configuration."""
model_adamw_betas = "betas"
"""Key to access the beta parameters used in AdamW."""
model_optimizer_adadelta = "Adadelta"
"""Key to access the Adadelta optimizer configuration."""
model_adadelta_rho = "rho"
"""Key to access the rho parameter used in Adadelta."""
model_constantlr = "ConstantLR"
"""Key to access the ConstantLR scheduler configuration."""
model_constantlr_lr_factor = "lr_factor"
"""Key to access the learning rate factor used in ConstantLR."""
model_cycliclr = "CyclicLR"
"""Key to access the CyclicLR scheduler configuration."""
model_ramplr = "RampLR"
"""Key to access the RampLR scheduler configuration."""
model_cycliclr_base_lr = "base_lr"
"""Key to access the base learning rate used in CyclicLR."""
model_cycliclr_max_lr = "max_lr"
"""Key to access the maximum learning rate used in CyclicLR."""
model_cycliclr_step_size_up = "step_size_up"
"""Key to access the number of steps for the up-cycle used in CyclicLR."""
model_cycliclr_mode = "mode"
"""Key to access the mode used for CyclicLR (e.g., 'triangular')."""
model_cycliclr_gamma = "gamma"
"""Key to access the gamma parameter for CyclicLR (affects scaling)."""
model_reduce_on_plateau = "ReduceLROnPlateau"
"""Key to access the ReduceLROnPlateau scheduler configuration."""
model_reduce_on_plateau_factor = "reduction_factor"
"""Key to access the learning rate reduction factor for ReduceLROnPlateau."""
model_reduce_on_plateau_patience = "patience"
"""Key to access the number of epochs with no improvement before reducing the learning rate."""
model_reduce_on_plateau_treshold = "threshold"
"""Key to access the relative threshold for reducing the learning rate."""
model_reduce_on_plateau_min_lr = "min_lr"
"""Key to acess the minimum learning rate."""
model_apply_with_caution = "apply_with_caution"
"""Key to access parameters related to selective training and parameter freezing."""
model_phase_param_learning = "phase_parameter_learning_bool"
"""Key to indicate if parameter learning should proceed in phases."""
model_param_groups_keywords = "phase_parameter_groups_by_keywords"
"""Key to access keyword-based parameter grouping for phased learning."""
model_length_of_phases = "length_of_phases_per_sequence"
"""Key to access the length of learning phases per epoch sequence."""
model_freeze_params = "freeze_parameters_for_training"
"""Key to access a list of parameters that should be frozen during training."""

